const toggleButton = document.getElementsByClassName('nav-btn')[0]
const navbarLinks = document.getElementsByClassName('navbar')[0]

toggleButton.addEventListener('click', () => {
  navbarLinks.classList.toggle('active')
})


function showCode() {
  let z = document.getElementById("bordCode").value;
  vraag1 = "Mummificatieperiode is een periode van 70 dagen waarin het stoffelijk overschot van de farao werd gemummificeerd. Hierna kon de begrafenis plaatsvinden. In het Oude Rijk werden farao's begraven in piramiden. In het Nieuwe Rijk werden de farao's begraven in de Vallei der Koningen, nabij Thebe. De mummificatie gebeurde in een Per Nefer, Oudegyptisch voor 'Mooi Huis'. Dit was meestal een tent, want hier bleef de lucht langer fris. Het lichaam werd op een houten tafel gelegd. De Egyptenaren gebruikten geen massieve tafels. Dat was makkelijker als ze de windsels om het lichaam moesten doen. Via een snee in de linkerzij werden alle interne organen verwijderd. De holten werden gewassen en werden dan volgepakt met natron. Het lichaam werd in een stapel natron begraven. De darmen, de longen, de lever en de maag werden gewassen in palmwijn en afzonderlijk bewaard in canopen (kruiken) en werden door de vier zonen van Horus (Amset, Doeamoetef, Hapy en Kebehsenoef) beschermd. Deze vazen werden meebegraven en waren vaak uitbundig versierd. Beroemd zijn de canopen van Toetanchamon. Het hart moest in het lichaam blijven zitten; dat was nodig bij de ceremonie van het wegen van het hart. Daarna werd het stoffelijk overschot 30 dagen in natron gelegd zodat het lichaam uitdroogde. Tot slot werd het lichaam in linnen doeken gewikkeld. Voor het lichaam begraven werd, werd het vaak nog versierd met sieraden en werden er zaden of vruchten meegegeven, vaak tussen het linnen. De mummie werd een masker opgedaan met zijn gezicht van goud. Het masker van Toetanchamon is een van de beroemdste. Het gemummificeerde lichaam werd in een of meer sarcofagen gelegd en daarna begraven (in mastaba, piramide of rotsgraf). Het mummificatieproces werd beschreven door Herodotus, een Griek, die Egypte bezocht."
  vraag2 = "De Egyptenaren geloofden vroeger in Goden. De oppergod was: Osiris, god van de landbouw en heerser van de onderwereld. Hij had ook een vrouw: Isis, de beschermgodin met toverkracht. Samen hadden ze een zoon: Horus, de hemelgod. Volgens oude verhalen was Osiris uit de hemel gekomen en werd de eerste koning van Egypte. Hij leerde de mensen hoe ze de grond moesten verbouwen, hoe ze moesten zaaien en oogsten. Er zijn wel meer dan 50 goden! Alle goden hadden een taak. Egyptische goden representeren meer dan 50 verschillende godheden. De stammen die in de oudheid de regio bevolkten aanbaden hun eigen afzonderlijke goden, die normaal gesproken het lichaam van een dier hadden. Terwijl de Egyptische beschaving avanceerde namen de godheden menselijke eigenschappen aan. In veel gevallen werden de goden afgebeeld met menselijke lichamen, maar behielden zij hun dierenhoofden. Maar, veranderingen in politieke machtsverhoudingen resulteerden in een veranderende status van de Egyptische goden. In het algemeen kan gezegd worden dat wanneer verschillende steden of regio's politiek dominanter werden, dat dan ook een bepaalde god dominanter werd."
  vraag3 = "In Egypte: in het dodenrijk werden de zielen van zondaars en goede menssen gescheiden. Wie goed leefde, kwam in een soort paradijs, waar overigens wel moest worden gewerkt. Navajo’s, Noord-Amerika: de ziel maakte een lange reis voor hij op de plaats van bestemming aankwam. Als ze bij een poel heeft gedronken krimpt ze ineen en steekt over naar het land van de geesten, waar ze van onstoffelijk voedsel leeft. Maya’s: Ah Puch is god van de dood. Hij heerste over de onderste onderwereld, de negende. Hier werd volop gefolterd. Ook de Azteken kenden negen onderwerelden."
  vraag4 = "Egypte had een ingewikkelde economie en een bestuur dat steeds meer uitbreidde. Hierdoor groeiden de verschillen tussen Egyptenaren in rijkdom, macht en aanzien. Het beroep bepaalde hoeveel macht en aanzien iemand had. Kinderen namen meestal het beroep van hun ouders over. Soms was het mogelijk om hogerop te komen, bijvoorbeeld door te leren schrijven. De Egyptische samenleving kan als een piramide in lagen worden verdeeld. De kleine toplaag bestond uit de farao en zijn familie, edelen, priesters en hoge ambtenaren. De middenlaag bestond uit de lage ambtenaren, ambachtslieden en handelaren. De onderste sociale laag werd gevormd door boeren, landarbeiders en slaven."
  vraag5 = "Omstreeks 3000 v.C. veranderde de landbouwsamenleving in Egypte in een landbouwstedelijke samenleving. Door de bloeiende landbouw groeide de bevolking en ontstond ruilhandel in landbouwoverschotten. Een deel van de bevolking specialiseerde zich in bepaalde ambachten. Dorpen groeiden uit tot steden, waar landbouw, ambachten en ruilhandel bij elkaar kwamen. De meeste mensen leefden als boer op het platteland, maar de stad was het centrum van een meer ingewikkelde economie."
  vraag6 = "Egyptische hiërogliefen is een schrift dat hoort bij de groep Logografisch schrift-soorten. De tekens bestaan uit symbolen die vooral de medeklinkers uitbeelden. De Egyptische hiërogliefen werden vooral geschreven door priesters. Het was een moeilijk schrift om te schrijven. Later gebruikten de Egyptenaren in plaats van hiërogliefen schrift het hiëratisch schrift en nog weer later het demotisch schrift. Die waren gemakkelijker te gebruiken. In het begin waren er zo'n 700 Egyptische hiërogliefen. Aan het eind waren dat er al zo'n 7000 tekens. In het begin stonden de tekens ook niet op een bepaalde (alfabetische) volgorde. Ook dat ontstond pas aan het eind van het gebruik. De meeste hiërogliefen zijn bekend uit de dodengraven en papyrusrollen over het leven na de dood. Deze laatste worden Egyptische dodenboeken genoemd."
  vraag7 = "Een farao is de naam voor een Oud Egyptische koning. Het woord Farao betekent 'man van het grote huis', waarmee de Egyptenaren het grote mooie paleis van de farao en zijn echtgenoot bedoelden. De Oude Egyptenaren geloofden in leven na de dood, daarom probeerden ze het leven van een dode koning zo leuk mogelijk te maken maar ook het leven zelf, door al zijn slaven te vermoorden en ook in zijn grafkamer te leggen. Maar de farao kreeg ook een heel erg mooi leven. Ze bouwden voor de farao's enorme piramides, maar omdat grafrovers die gemakkelijk konden vinden en plunderen, begonnen de Oude Egyptenaren later tomben te bouwen in het dal der Koningen. Het werkte; hoewel ook daar nog graven werden leeggeroofd, bleven er ook veel onontdekt door de grafrovers. De bekendste daarvan is Toetanchamon, die als farao niet veel bijzonders heeft gedaan (stierf al jong) maar wel werd begraven met een enorme schat. Hij was de zoon van Echnaton. Dat was een bijzondere farao omdat hij in plaats heel veel goden, maar één god wilde aanbidden. Dat was de zon. Rond die tijd heeft Mozes geleefd, dus het is mogelijk dat ze elkaar hebben beïnvloed."
  vraag8 = "Een piramide is een grafmonument of een graftombe voor Egyptische farao’s, de vroegere heersers van Egypte. Hoewel na het overlijden farao’s met hun kostbaarheden en persoonlijke bezittingen in een piramide werden gelegd, vonden archeologen alleen kostbaarheden en geen enkel spoor van een farao. De eerste piramide werd ruim 4500 jaar geleden gebouwd. In totaal zijn ongeveer 80 Egyptische piramiden bewaard gebleven. Ze zijn gebouwd over een periode van ongeveer 1000 jaar. In piramides werden farao's gelegd als ze dood zijn. Meestal helemaal bovenin. In de piramide liggen ook allemaal offers. In Egypte gebruikten ze piramides om hun koningen in te begraven. De Egyptenaren noemden hun koning farao. Ze geloofden dat de farao een god was, die naar de aarde was afgedaald. Na zijn dood zou de farao terugkeren naar de hemel. Maar de farao zou alleen in de hemel kunnen leven als zijn lichaam op aarde bleef bestaan. Als je dood gaat vergaat je lichaam. De Egyptenaren deden allerlei dingen met het lichaam om het te kunnen bewaren. Ze maakten een mummie van het lichaam. Eerst werden de zachte delen uit het lichaam gehaald, zoals de hersenen , de longen ,lever enz. want die kunnen verrotten. Alleen het hart bleef bewaart want die zou hij nog nodig hebbenDaarna werd het lichaam 40 dagen lang in het zout gelegd en werd het gewikkeld in repen linnen. Daarna werd het lichaam in een mooi versierde houten kist gelegd. Deze kisten hadden vaak de vorm van een mummie. De mummie werd dan in de kist in de grafkamer van de piramide begraven. Er werd eten en drinken bij hem neergezet en de voorraadkamers werden gevuld met prachtige meubels, kleren en sieraden die de koning in zijn volgende leven in de hemel nog zou kunnen gebruiken. Als laatste werd de piramide door grote steenblokken afgesloten om het lichaam tegen rovers te beschermen. De geest van de farao kon nu vanuit de piramide naar de hemel vertrekken. Hij kon de piramide als een soort trap naar de hemel gebruiken. Archeologen zoeken nog steeds naar nieuwe piramides. De wetenschappers graven en speuren. Soms hebben ze geluk, zoals in 2008. Bij Sakkara vonden ze iets. De piramide was beschadigt, maar het belangrijkste deel, de grafkelder, was nog heel. In de grafkelder vonden onderzoekers het lichaam van koningin Shesheshe. Zij leefde 4300 jaar geleden. De piramide was bedolven onder woestijnzand. Dat komt door zandstormen, die vaak voorkomen in de woestijn."
  vraag9 = "De Nijl is een bekende rivier die door het oosten van Afrika stroomt. De rivier is wel 6695 km lang. Het is daarom samen met de Amazone in Zuid-Amerika een van de twee langste rivieren ter wereld. Welke van de twee nou precies het langst is, daarover zijn de mensen het niet helemaal eens. Het bekendst is natuurlijk het stuk van de Nijl dat door Egypte loopt. In het noorden van Egypte komt de Nijl uit in de Middellandse Zee. Maar het begin van de rivier ligt in twee verschillende grote meren. Het ene meer is het Tanameer in Ethiopië. Van daaruit stroomt een rivier die de 'Blauwe Nijl' wordt genoemd. In het Victoriameer, op de grens tussen Tanzania, Kenia en Oeganda begint een andere rivier, die de 'Witte Nijl' wordt genoemd. Via Zuid-Soedan stroomt de Witte Nijl naar Soedan, daar komen de Blauwe en de Witte Nijl bij elkaar in 1 grote rivier. Vanaf daar wordt de rivier gewoon de Nijl genoemd."
  vraag10 = "De tombe van Toetanchamon is in 1922 ontdekt door Howard Carter. Er zijn heel veel schatten gevonden in het graf. De kostbaarste schat die in het graf van de jonge koning lag is het massief gouden masker. Het lichaam van de farao is gemummificeerd en lag begraven in laatste kamer van de tombe. Mummificeren is het drogen van een lichaam, en het verwijderen van de ingewanden. Vervolgens worden die in kleien potjes in de vorm van dieren gestopt (de Canopen, zie afbeelding). Daarna wordt het gedroogde lichaam met allerlei stoffen en kruiden ingesmeerd zodat het niet wegrot en niet stinkt. Daarna wordt het strak in zwachtels gewikkeld en blijft het soms wel duizenden jaren goed. Er zijn vier kamers. De eerste is de voorkamer, de tweede de zijkamer, de derde de grafkamer (waar de farao lag) en de vierde de schatkamer (waar de schat lag)."
  vraag11 = "Sarcofaag komt van het Griekse woord sarkophagus, wat 'vleesetend' betekent. Een sarcofaag is oorspronkelijk een steensoort waarvan men grafkisten maakte, waarin de lichamen, uitgezonderd de tanden, binnen veertig dagen verteerden. Later werd sarcofaag de benaming voor alle stenen of terracotta doodskisten en tenslotte werd de sarcofaag voornamelijk gebruikt voor die lichamen die men niet begroef, maar die als monument zichtbaar bleven. In Griekenland vindt men sarcofagen al sinds de Mykeense tijd, deze zijn dan zo kort dat een lijk er gehurkt in lag. In de zevende eeuw voor Christus kwamen de sarcofagen uit Klein-Azië weer in gebruik. In Griekenland zijn geen sarcofagen uit de klassieke tijd aangetroffen, maar wel des te meer uit de Hellenistische tijd. De oudste Romeinse sarcofaag is die van C. Scipio Barbatus (298 voor Christus). Het beeldhouwwerk dat de sarcofaag versiert geeft meestal Griekse mythen weer. Soms vertoont de hoofdpersoon de trekken van de dode. De christenen hebben het gebruik van sarcofagen overgenomen, zo kwamen ze veelvuldig voor in de Middeleeuwen en in de Renaissance."
  vraag12 = "Een farao is de naam voor een Oud Egyptische koning. Het woord Farao betekent 'man van het grote huis', waarmee de Egyptenaren het grote mooie paleis van de farao en zijn echtgenoot bedoelden. De Oude Egyptenaren geloofden in leven na de dood, daarom probeerden ze het leven van een dode koning zo leuk mogelijk te maken maar ook het leven zelf, door al zijn slaven te vermoorden en ook in zijn grafkamer te leggen. Maar de farao kreeg ook een heel erg mooi leven. Ze bouwden voor de farao's enorme piramides, maar omdat grafrovers die gemakkelijk konden vinden en plunderen, begonnen de Oude Egyptenaren later tomben te bouwen in het dal der Koningen. Het werkte; hoewel ook daar nog graven werden leeggeroofd, bleven er ook veel onontdekt door de grafrovers. De bekendste daarvan is Toetanchamon, die als farao niet veel bijzonders heeft gedaan (stierf al jong) maar wel werd begraven met een enorme schat. Hij was de zoon van Echnaton. Dat was een bijzondere farao omdat hij in plaats heel veel goden, maar één god wilde aanbidden. Dat was de zon. Rond die tijd heeft Mozes geleefd, dus het is mogelijk dat ze elkaar hebben beïnvloed."
  vraag13 = "Er werd pas een piramide gebouwd als er een nieuwe farao was. Dan gingen er wel 100.000 mensen aan de piramide werken. De mensen die de piramide maakten waren boeren en arbeiders van de farao. Piramides werden gebouwd met grote stenen die uit een steengroeve werden gehaald. Één steen kon wel 2500 kilo wegen en om 1 piramide te maken waren er ongeveer 2 miljoen van deze stenen nodig. Maar wetenschappers hebben ontdekt dat niet alle stenen uit de steengroeve kwamen. Sommige stenen zijn gemaakt door de Egyptenaren. Dit hebben ze gedaan door een soort klei, asresten en zout te mengen en dan te laten drogen op de plek waar de steen kwam te liggen. De 'nep' stenen liggen alleen bovenin in de piramide, omdat dit de moeilijkste stenen waren om neer te leggen. Om deze zware stenen van de steengroeve naar de piramide te krijgen werden ze eerst over de rivier de Nijl naar de piramide gebracht. Daarom staan de piramides ook dichtbij de Nijl. De Egyptenaren hadden speciale boten gemaakt om de stenen te vervoeren. Om de stenen op het land te verplaatsen legden ze boomstammen neer en bonden ze een touw om de steen heen, ze maakten een slee. Met een paar mensen trokken ze de steen naar de piramide toe. Om de piramide hadden ze een grote heuvel gemaakt. De heuvel werd gemaakt van cement, zand en hout. Met de heuvel konden ze de stenen makkelijker omhoog trekken en ook op de goede plek. Bij sommige piramides maakten de Egyptenaren de grond nat, zodat het zand op de goede plek bleef liggen en ze de stenen nog makkelijker omhoog konden trekken. De piramide was af als de laatste steen bovenin de piramide bij de grafkamer was neergelegd. De mensen die aan de piramide werkten waren dan nog niet klaar, want ze moesten eerst de heuvel om de piramide weghalen. Als de heuvel weg was gehaald gingen ze de stenen glad vijlen. Ze vijlden net zo lang totdat de stenen glinsterde in de zon. Deze piramide heeft de naam gladde piramide. Er zijn ook trappiramides. Een trappiramide werd gebouwd door 3 tot 6 gladde piramides op elkaar te bouwen. Er staan vaak ook een paar kleine piramides bij een grote piramide. De kleine piramides zijn voor de koninginnen van de farao."
  vraag14 = "Gelukkig stond de farao er niet alleen voor. Er waren een heleboel ambtenaren die de farao bijstonden in het dagelijks bestuur van het rijk. Egypte was dan ook een echte bureaucratie (= een heerschappij van ambtenaren). De meeste ambtenaren hadden banden met de koninklijke familie. Maak even kennis met de belangrijkste functies in het Egyptisch rijk: Aan de top van de ambtenaren stond de vizier. Hij regelde praktische zaken en trad op als hoogste rechter. Het Egyptisch rijk bestond uit ongeveer veertig gouwen (= een kleiner gebied, te vergelijken met een provincie). Aan het hoofd van elke gouw stond een gouwvorst.  Het deel 'vorst' in hun naam wijst op hun belangrijkheid. Onder machtige farao's waren gouwvorsten volgzaam, maar in tussenperiodes maakten zij misbruik van de zwakheid van de farao's. Schrijvers maten de velden op en noteerden de landbouwopbrengsten. Dat was nodig om de belastingen in natura te betalen. De Egyptenaren moesten een deel van hun landbouwopbrengsten afgeven aan de staat. Schatbewaarders sloegen de belastingen op in magazijnen en tempels. Priesters leidden de religieuze diensten en regelden de opbrengsten van de tempel. Allerlei goederen werden binnen de tempel opgeslagen en verhandeld: dit heet tempeleconomie. "
  vraag15 = "Alexander de Grote maakt een eind aan Egyptische cultuur. Uiteindelijk luidde de komst van een nieuwe speler op het wereldtoneel de ondergang van het Oude Egypte in. Alexander de Grote kwam uit Macedonië, en zijn verovering van Egypte in 332 v.Chr. maakte een einde aan drieduizend jaar Oud-Egyptische cultuur."
  fout = "Fout: Dit is geen werkende code, probeer het opnieuw met een goede code uit het bordspel."
  if(z == 1234){
    document.getElementById("informatie").innerHTML = vraag1;
  } else if (z == 3456) {
    document.getElementById("informatie").innerHTML = vraag2;
  } else if (z == 4567) {
    document.getElementById("informatie").innerHTML = vraag3;
  } else if (z == 5678) {
    document.getElementById("informatie").innerHTML = vraag4;
  } else if (z == 6789) {
    document.getElementById("informatie").innerHTML = vraag5;
  } else if (z == 7891) {
    document.getElementById("informatie").innerHTML = vraag6;
  } else if (z == 9510) {
    document.getElementById("informatie").innerHTML = vraag7;
  } else if (z == 2594) {
    document.getElementById("informatie").innerHTML = vraag8;
  } else if (z == 9137) {
    document.getElementById("informatie").innerHTML = vraag9;
  } else if (z == 7530) {
    document.getElementById("informatie").innerHTML = vraag10;
  } else if (z == 1469) {
    document.getElementById("informatie").innerHTML = vraag11;
  } else if (z == 1337) {
    document.getElementById("informatie").innerHTML = vraag12;
  } else if (z == 7463) {
    document.getElementById("informatie").innerHTML = vraag13;
  } else if (z == 1793) {
    document.getElementById("informatie").innerHTML = vraag14;
  } else if (z == 7823) {
    document.getElementById("informatie").innerHTML = vraag15;
  } else {
    document.getElementById("informatie").innerHTML = fout;
  }

}